export * from 'src/shared/components/ui/ContainerWrapper'
export * from 'src/shared/components/ui/CRating'
export * from '@/shared/components/ui/Error/'
export * from '@/shared/components/ui/ThePagination'
export * from 'src/shared/components/ui/CLoader'
export * from '@/shared/components/ui/ThemeButton'
export * from '@/shared/components/icons'